apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    name: master
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - protocol: TCP
    name: agent
    port: 50000
    targetPort: 50000
    nodePort: 30081


# kubectl port-forward svc/jenkins-service 8080:8080 -n jenkins

