jenkins:
  numExecutors: 2
  mode: NORMAL
  systemMessage: "Configured by Jenkins Configuration as Code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin_password"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  clouds:
    - kubernetes:
        name: "Kubernetes Cloud"
        serverUrl: "https://kubernetes.default.svc"
        jenkinsTunnel: "jenkins-service:50000"  # If Jenkins is running inside Kubernetes, this will typically be the internal Jenkins service
        containerCap: 10  # Maximum number of containers Jenkins can create
        connectTimeout: 5
        readTimeout: 5
        skipTlsVerify: false
        templates:
          - name: "jnlp-agent"
            label: "jnlp-agent"
            containerTemplate:
              name: "jnlp-agent"
              image: "jenkins/inbound-agent:latest"
              workingDir: "/home/jenkins/agent"
              command: "cat"  # Required for the inbound agent to work
              ttyEnabled: true
              resourceRequestCpu: "100m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "1"
              resourceLimitMemory: "2Gi"
              envVars:
                - name: "JAVA_OPTS"
                  value: "-Xmx1024m"
  crumbIssuer:
    standard: true
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io"
  views:
    - name: "All"
  scmCheckoutRetryCount: 3

jobs:
  - pipelineJob:
      name: "MyPipelineJob"
      definition:
        cpsScm:
          scm:
            git:
              branches: 
                - "*/main"
              extensions: []
              remote: 'https://github.com/ankit-cn-47/jenkins-dynamic'
              credentialsId: 'github-credentials'  # Replace with your GitHub credentials ID
          scriptPath: "jenkins/jenkinsfile"
