jenkins:
  numExecutors: 2
  mode: NORMAL
  systemMessage: "Configured by Jenkins Configuration as Code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin_password"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  clouds:
    - kubernetes:
        name: "Kubernetes Cloud"
        serverUrl: "https://kubernetes.default.svc"
        containerCapStr: "10"  # Maximum number of containers (pods) that Jenkins can launch simultaneously
        connectTimeout: 5
        templates:
          - name: "jnlp-agent"
            image: "jenkins/inbound-agent:latest"  # Use the inbound agent image or another image of your choice
            workingDir: "/home/jenkins/agent"
            command: "cat"  # Required, as the pod runs as an agent container
            ttyEnabled: true
            resourceRequestCpu: "100m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "2Gi"
            envVars:
              - key: "JAVA_OPTS"
                value: "-Xmx1024m"
  crumbIssuer:
    standard: true
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io"
  views:
    - all:
        name: "All"
  scmCheckoutRetryCount: 3

jobs:
  - pipelineJob:
      name: "MyPipelineJob"
      definition:
        cpsScm:
          scm:
            git:
              branches: 
                - "*/main"
              extensions: []
              remote: 'https://github.com/ankit-cn-47/jenkins-dynamic'
              credentialsId: 'github-credentials'  # Replace with your GitHub credentials ID
          scriptPath: "jenkins/jenkinsfile"
