credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-credentials"
              password: "{AQAAABAAAAAwAOmzDF/ztlBjQYPoLzzOz+4UH2UuI00Xdlc0ZJM3YitZg0CGtK+qiuXSG2aXmWnIFJ2GriyPDs+e/tLhCclP2w==}"
              scope: GLOBAL
              username: "ankit-cn-47"

jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
    - kubernetes:
        containerCap: 10
        name: "Kubernetes"
        namespace: "jenkins"
        serverUrl: "https://kubernetes.docker.internal:6443"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  numExecutors: 2
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - name: "All"
      description: "All views"

jobs:
  - pipelineJob:
      name: "NodeJS-job"
      definition:
        cpsScm:
          scm:
            git:
              branches:
                - "*/main"
              remote: 'https://github.com/ankit-cn-47/jenkins-dynamic'
              credentialsId: 'github-credentials'
          scriptPath: "jenkins/jenkinsfile"
