jenkins:
  numExecutors: 2
  mode: NORMAL
  systemMessage: "Configured by Jenkins Configuration as Code (JCasC)"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin_password"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  clouds:
    - kubernetes:
        name: "Kubernetes Cloud"
        serverUrl: "https://kubernetes.default.svc"
        containerCapStr: "10"
        connectTimeout: 5
        templates:
          - name: "jnlp-agent"
            image: "jenkins/inbound-agent:latest"
            workingDir: "/home/jenkins/agent"
            command: "cat"
            ttyEnabled: true
            resourceRequestCpu: "100m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "2Gi"
            envVars:
              - envVar:
                  key: "JAVA_OPTS"
                  value: "-Xmx1024m"
        namespace: "jenkins"
  crumbIssuer:
    standard: true
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io"
  views:
    - all:
        name: "All"
  scmCheckoutRetryCount: 3

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-credential"
              description: "GitHub credentials using PAT"
              username: "your_github_username"  # Placeholder, already stored in Jenkins
              password: "your_github_pat"  # Placeholder, already stored in Jenkins

jobs:
  - pipelineJob:
      name: "MyPipelineJob"
      definition:
        cpsScm:
          scm:
            git:
              branches: 
                - "*/main"
              extensions: []
              remote: 'https://github.com/ankit-cn-47/jenkins-dynamic.git'
              credentialsId: 'github-credential'
          scriptPath: "jenkins/jenkinsfile"
