jenkins:
  numExecutors: 2
  mode: NORMAL
  systemMessage: "Configured by Jenkins Configuration as Code (JCasC)"
  securityRealm:
    local:
      users:
        - id: "admin"
          password: "admin_password"
          permissions:
            - "admin"
  authorizationStrategy:
    anyoneCanDoJob: false
    allowAnonymousRead: false
  clouds: []
  crumbIssuer:
    enable: true
  updateCenter:
    updateSite: "https://updates.jenkins.io"
  views:
    - name: "All"
      filter: "All"
  scmCheckoutRetryCount: 3

jobs:
  - script: |
      pipeline {
        agent any
        stages {
          stage('Checkout') {
            steps {
              git credentialsId: 'github-credentials-id', url: 'https://github.com/ankit-cn-47/jenkins-dynamic'
            }
          }
          stage('Run Jenkinsfile') {
            steps {
              script {
                def jenkinsfile = load 'jenkins/jenkinsfile'
                echo "Executing Jenkinsfile from repository"
                jenkinsfile()
              }
            }
          }
        }
      }
