apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: jenkins  # Change this to your desired namespace
data:
  # .dockerconfigjson: <base64-encoded-dockerconfigjson>
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbmtpdGNoYW5kcmE0NyIsInBhc3N3b3JkIjoiUXBhbHptQDEwMjkzODUiLCJlbWFpbCI6ImFua2l0c2luZ2hjaGFuZHJhQGdtYWlsLmNvbSIsImF1dGgiOiJZVzVyYVhSamFHRnVaSEpoTkRjNlVYQmhiSHB0UURFd01qa3pPRFU9In19fQ==
type: kubernetes.io/dockerconfigjson


# kubectl create secret docker-registry regcred \
#   --docker-server=https://index.docker.io/v1/ \
#   --docker-username=ankitchandra47 \
#   --docker-password=Qpalzm@1029385 \
#   --docker-email=ankitsinghchandra@gmail.com
# kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=ankitchandra47 --docker-password=Qpalzm@1029385 --docker-email=ankitsinghchandra@gmail.com