apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: application
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80        # Expose on port 80 inside the cluster
      targetPort: 3000  # Map to container port 3000
  type: NodePort  # Change to NodePort if using Minikube or Docker Desktop