name: Main CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  security-scan:
    uses: ./.github/workflows/security-scan.yml

  static-lint:
    uses: ./.github/workflows/static-lint.yml
