name: Static Code Analysis and Linters

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          pip install flake8 bandit -r requirements.txt
          npm install eslint --save-dev

      - name: Run Python Linting (Flake8)
        run: flake8 .

      - name: Run Python Security Scan (Bandit)
        run: bandit -r .

      - name: Run Node.js Linting (ESLint)
        run: npx eslint .
